# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autofalloff/assets/basic_layout.ui'
#
# Created: Fri Mar 25 10:19:11 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(450, 100, 171, 16))
        self.label.setObjectName("label")
        self.labelSourcePaddle = QtGui.QLabel(self.centralwidget)
        self.labelSourcePaddle.setGeometry(QtCore.QRect(560, 100, 51, 16))
        self.labelSourcePaddle.setObjectName("labelSourcePaddle")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(440, 120, 111, 16))
        self.label_4.setObjectName("label_4")
        self.labelStagePosition = QtGui.QLabel(self.centralwidget)
        self.labelStagePosition.setGeometry(QtCore.QRect(560, 160, 91, 16))
        self.labelStagePosition.setObjectName("labelStagePosition")
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 300, 261, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.frame_2 = QtGui.QFrame(self.verticalLayoutWidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(300, 300, 261, 261))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.frame_3 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2.addWidget(self.frame_3)
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(610, 300, 261, 261))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.frame_4 = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.buttonStart = QtGui.QPushButton(self.centralwidget)
        self.buttonStart.setGeometry(QtCore.QRect(40, 80, 90, 27))
        self.buttonStart.setObjectName("buttonStart")
        self.buttonStop = QtGui.QPushButton(self.centralwidget)
        self.buttonStop.setGeometry(QtCore.QRect(40, 120, 90, 27))
        self.buttonStop.setObjectName("buttonStop")
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(170, 100, 221, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(170, 130, 221, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(170, 160, 221, 16))
        self.label_11.setObjectName("label_11")
        self.buttonInitialize = QtGui.QPushButton(self.centralwidget)
        self.buttonInitialize.setGeometry(QtCore.QRect(40, 40, 90, 27))
        self.buttonInitialize.setObjectName("buttonInitialize")
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(230, 40, 251, 16))
        self.labelStatus.setObjectName("labelStatus")
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(170, 40, 59, 15))
        self.label_12.setObjectName("label_12")
        self.labelReferencePaddle = QtGui.QLabel(self.centralwidget)
        self.labelReferencePaddle.setGeometry(QtCore.QRect(560, 120, 51, 16))
        self.labelReferencePaddle.setObjectName("labelReferencePaddle")
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(440, 160, 111, 16))
        self.label_14.setObjectName("label_14")
        self.labelPaddleController = QtGui.QLabel(self.centralwidget)
        self.labelPaddleController.setGeometry(QtCore.QRect(350, 100, 51, 16))
        self.labelPaddleController.setObjectName("labelPaddleController")
        self.labelStageController = QtGui.QLabel(self.centralwidget)
        self.labelStageController.setGeometry(QtCore.QRect(350, 130, 51, 16))
        self.labelStageController.setObjectName("labelStageController")
        self.labelCameraController = QtGui.QLabel(self.centralwidget)
        self.labelCameraController.setGeometry(QtCore.QRect(350, 160, 51, 16))
        self.labelCameraController.setObjectName("labelCameraController")
        self.textLog = QtGui.QTextEdit(self.centralwidget)
        self.textLog.setGeometry(QtCore.QRect(640, 30, 321, 241))
        self.textLog.setObjectName("textLog")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Source Paddle:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSourcePaddle.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Reference Paddle", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStagePosition.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Reference", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Combined", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonStart.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonStop.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Paddle Controller Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Stage controller status:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Camera controlelr status:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonInitialize.setText(QtGui.QApplication.translate("MainWindow", "Initialize", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStatus.setText(QtGui.QApplication.translate("MainWindow", "Pre-initialization", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelReferencePaddle.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Stage Position:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPaddleController.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStageController.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCameraController.setText(QtGui.QApplication.translate("MainWindow", "Pre-init", None, QtGui.QApplication.UnicodeUTF8))

