# Based heavily on:
# http://tjelvarolsson.com/blog/how-to-continuously-test-your-python-code-on-windows-using-appveyor/

environment:
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda

platform:
  - x64

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  - conda create --name autofalloff_conda pyside
  - activate autofalloff_conda


  # The exact steps here are born from hours of environment comparison
  # and testing. As of 2016-10-24 16:21, this appears to be the set of
  # required steps to build the application that will run on bare bones
  # windows 10 install.

  - conda remove setuptools

  - conda install numpy

  - conda install pywin32

  # No conda packages for these:
  - pip install pefile
  - pip install pyinstaller

  - conda install pyside
  - conda install six
  - conda install distribute
  - conda install pillow
  - conda install pyqtgraph
  - conda install pyserial

  # For matching with a local build environment
  - conda list

  - choco install -y InnoSetup
  - set PATH="C:\Program Files (x86)\Inno Setup 5";%PATH%

# Build is off because it is not applicable to python
build: off

test_script:
  # Run the project tests
     - "python setup.py develop"
     - "py.test -s"

after_test:

   # For matching with a local build environment
   - conda list

   - "pyinstaller \
      --clean \
      --distpath=scripts/built-dist \
      --workpath=scripts/work-path \
      --noconfirm \
      --icon autofalloff/assets/images/ApplicationIcon.ico \
      --specpath scripts \
      scripts/AutoFallOff.py"
      
   - "iscc scripts\\Application_InnoSetup.iss"
   - ps: "ls scripts\\built-dist\\*.exe"
   - ps: "ls scripts\\windows_installer\\*.exe"

   - ps: "7z a AutoFallOff.zip scripts\\built-dist"

artifacts:
   - path: AutoFallOff.zip
   - path: scripts\windows_installer\*.exe
